name: Run tests

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install dependencies
        run: yarn install
      - name: eslint
        run: yarn lint
      - name: Unit tests
        run: yarn test-unit
